% Roxanne Lutz
% MATH375
% 9/25/2025
% HW3

% on-run cleanup tasks
clc, clearvars, close all;

tolerance = 10 ^ (-8); % tolerance specified 
iterations = 30; % chosen arbitrarily to get approximation
x_start = 1; % lower bound on interval to find root in
x_end = 2; % upper bound on interval to find root in 

[x_mids, y_mids, iterations_needed, success] = ...
    bisectionMethod(tolerance, iterations, x_start, x_end, @(x) function_02(x));

% print success if we've found a zero within iterations and tolerance
if success;
    disp( ...
        "BISECTION: Approximate root found successfully in " ...
        + iterations_needed ...
        + " iterations: x = " ...
        + x_mids(end) ...
        );
    % disp("root found: x = " + x_mids(end));

else;
    disp( ...
        "BISECTION: Approximate root was NOT found within tolerance in " ...
        + iterations + " iterations." ...
        );
end;

% get exact values of function to find root of
h = 0.001; start_pt = -3; end_pt =  3; % initilization values
x_exact = [start_pt:h:end_pt]; % calucluate exact for these vals of x
y_exact = zeros(size(x_exact)); % preallocate memory
counter = 1;

for x = x_exact;
    [y_exact(counter), ~] = function_02(x);
    counter = counter + 1;
end;

% plot the exact graph versus the approximation points
figure(1);
plot(x_exact, y_exact, "--c", ...
    x_mids, y_mids, "oy", ...
    x_start, function_02(x_start), "og", ...
    x_end, function_02(x_end), "ob", ...
    x_mids(end), y_mids(end), "or", ...
    LineWidth=1.5);
hold on;

legend( ...
    'Exact Values of f(x)', ...
    '(x, y) Approx Midpoints', ...
    'Initial Starting Interval Value', ...
    'Initial Ending Interval Value', ...
    'Final Approximation' ...
    );
title('Derived f(x) vs Approximations to the Root using Bisection Method');
xlabel("Domain, [" + start_pt + ", " + end_pt + "] with h = " + h);
ylabel('Range, output of f(x) and Approximations');
grid on;

% lets compare the iterations of bisection to newton's briefly

x_init = 1; % init value close to root

% run newtons method with given method
[x_approx, y_approx, iterations_needed, success] = ...
    newtonsMethod(tolerance, iterations, x_init, @(x) function_02(x));

% print success if we've found a zero within iterations and tolerance
if success;
    disp( ...
        "NEWTON: Approximate root found successfully in " ...
        + iterations_needed ...
        + " iterations: x = " ...
        + x_approx(end) ...
        );
else;
    disp( ...
        "NEWTON: Approximate root was NOT found within tolerance in " ...
        + iterations + " iterations." ...
        );
end;

% plot the exact graph versus the approximation points
figure(2);
plot(x_exact, y_exact, "--c", ...
    x_approx, y_approx, "oy", ...
    x_approx(1), y_approx(1), "og", ...
    x_approx(end), y_approx(end), "or", ...
    LineWidth=1.5);
hold on;

legend( ...
    'Exact Values of f(x)', ...
    "Approximations to the Root with Newton's Method", ...
    "Initial Guess, x = " + x_init, ...
    "Final Approximation" ...
    );
title("Exact f(x) vs Approximations to the Root using Newton's Method");
xlabel("Domain, [" + start_pt + ", " + end_pt + "] with h = " + h);
ylabel('Range, output of f(x) and Approximations');
grid on;
