% Roxanne Lutz
% MATH375
% 9/30/2025
% HW3

% on-run cleanup tasks
clc, clearvars, close all;

tolerance = 10 ^ (-8); % tolerance chosen to be sufficiently close to
iterations = 100; % chosen arbitrarily to get approximation
x_init = 1; % initial guess specified by problem

% run newtons method with given method
[x_approx, y_approx, iterations_needed, success] = ...
    newtonsMethod(tolerance, iterations, x_init, @(x) function_03(x));

% print success if we've found a zero within iterations and tolerance
if success;
    disp( ...
        "NEWTON: Approximate root found successfully in " ...
        + iterations_needed ...
        + " iterations: x = " ...
        + x_approx(end) ...
        );
else;
    disp( ...
        "Approximate root was NOT found within tolerance in " ...
        + iterations + " iterations." ...
        );
end;


% get exact values of function to find root of

h = 0.0001; % higher accuracy chosen here for better graph, changes highly on h
start_pt_more = min(x_approx); end_pt_more = max(x_approx); % initilization values full range

% get the larger range graph
x_exact_more = [start_pt_more:h:end_pt_more]; % calucluate exact for these vals of x
y_exact_more = zeros(size(x_exact_more)); % preallocate memory
counter = 1;

for x = x_exact_more;
    [y, dy] = function_03(x);
    y_exact_more(counter) = y;
    counter = counter + 1;
end;

% plot the exact graph versus the approximation points
figure(1);
plot(x_exact_more, y_exact_more, "--c", ...
    x_approx, y_approx, "oy", ...
    x_approx(1), y_approx(1), "og", ...
    x_approx(end), y_approx(end), "or", ...
    LineWidth=1.5);
hold on;

legend( ...
    'Exact Values of f(x)', ...
    "Approximations to the Root with Newton's Method", ...
    "Initial Guess, x = " + x_init, ...
    "Final Approximation" ...
    );
title("Exact f(x) vs Approximations to the Root using Newton's Method");
xlabel("Domain, [" + start_pt_more + ", " + end_pt_more + "] with h = " + h);
ylabel('Range, output of f(x) and Approximations');
ylim([min(y_approx), max(y_approx)]); % for some semblance of sanity
xlim([min(x_approx), max(x_approx)]);

grid on;

% get the lesser graph for more focused viewing

start_pt_less = 0; end_pt_less = 2; % initilization values less range

x_exact_less = [start_pt_less:h:end_pt_less]; % calucluate exact for these vals of x
y_exact_less = zeros(size(x_exact_less)); % preallocate memory
counter = 1;

for x = x_exact_less;
    [y, dy] = function_03(x);
    y_exact_less(counter) = y;
    counter = counter + 1;
end;

% plot the exact graph versus the approximation points
figure(2);
plot(x_exact_less, y_exact_less, "--c", ...
    x_approx, y_approx, "oy", ...
    x_approx(1), y_approx(1), "og", ...
    x_approx(end), y_approx(end), "or", ...
    LineWidth=1.5);
hold on;

legend( ...
    'Exact Values of f(x)', ...
    "Approximations to the Root with Newton's Method", ...
    "Initial Guess, x = " + x_init, ...
    "Final Approximation" ...
    );
title("Exact f(x) vs Approximations to the Root using Newton's Method");
xlabel("Domain, [" + start_pt_less + ", " + end_pt_less + "] with h = " + h);
ylabel('Range, output of f(x) and Approximations');
ylim([-10, 10]); % for some semblance of sanity
xlim([start_pt_less, end_pt_less]);

grid on;

% extra: try with bisection method from 0 -> 2

x_start = 0.5; % lower bound on interval to find root in
x_end = 1; % upper bound on interval to find root in 

[x_mids, y_mids, iterations_needed, success] = ...
    bisectionMethod(tolerance, iterations, x_start, x_end, @(x) function_03(x));

% print success if we've found a zero within iterations and tolerance
if success;
    disp( ...
        "BISECTION: Approximate root found successfully in " ...
        + iterations_needed ...
        + " iterations: x = " ...
        + x_mids(end) ...
        );
    % disp("root found: x = " + x_mids(end));

else;
    disp( ...
        "Approximate root was NOT found within tolerance in " ...
        + iterations + " iterations." ...
        );
end;


% plot the exact graph versus the approximation points (BISECTION)
figure(3);
plot(x_exact_more, y_exact_more, "--c", ...
    x_mids, y_mids, "oy", ...
    x_start, function_03(x_start), "og", ...
    x_end, function_03(x_end), "ob", ...
    x_mids(end), y_mids(end), "or", ...
    LineWidth=1.5);
hold on;

legend( ...
    'Exact Values of f(x)', ...
    '(x, y) Approx Midpoints', ...
    'Initial Starting Interval Value', ...
    'Initial Ending Interval Value', ...
    'Final Approximation' ...
    );
title("Exact f(x) vs Approximations to the Root using Bisection Method");
xlabel("Domain, [" + start_pt_more + ", " + end_pt_more + "] with h = " + h);
ylabel('Range, output of f(x) and Approximations');
ylim([min(y_approx), max(y_approx)]); % for some semblance of sanity
xlim([min(x_approx), max(x_approx)]);

grid on;


% plot the exact graph versus the approximation points
figure(4);
plot(x_exact_less, y_exact_less, "--c", ...
    x_mids, y_mids, "oy", ...
    x_start, function_03(x_start), "og", ...
    x_end, function_03(x_end), "ob", ...
    x_mids(end), y_mids(end), "or", ...
    LineWidth=1.5);
hold on;

legend( ...
    'Exact Values of f(x)', ...
    '(x, y) Approx Midpoints', ...
    'Initial Starting Interval Value', ...
    'Initial Ending Interval Value', ...
    'Final Approximation' ...
    );
title("Exact f(x) vs Approximations to the Root using Bisection Method");
xlabel("Domain, [" + start_pt_less + ", " + end_pt_less + "] with h = " + h);
ylabel('Range, output of f(x) and Approximations');
ylim([-10, 10]); % for some semblance of sanity
xlim([start_pt_less, end_pt_less]);

grid on;
